### ISSUE TITLE
Menu completly broken

### ISSUE THREAD

**Issue by Blueberryy** [Gaerisson/Gmod-Custom-Menu#8]
Can't click any button
![menu_bug](https://user-images.githubusercontent.com/36592509/79047793-5dac3f80-7c32-11ea-9c47-c31d1d4a323f.png)
I restarted game 2 times tho

**Comment by Gaerisson** [comment]
I tried on my Gmod, it is working fine :/ can you open your game with the console (-console in launch parameter) and send me a screenshot or try to replace all files again to be sure that no files has been skipped !

**Comment by Blueberryy** [comment]
I veryfied game files then reinstalled. Still not working

**Comment by Gaerisson** [comment]
I checked with my game, in fact, this issue appear when you're not using the beta (x86-64) of the game, because the browser engine is old (not chromium)
So you have to go in beta x86-64 (see image bellow), I think I will not fix it for the old web browser engine cause in some month (I hope) facepunch will deploy the chromium by default.

![image](https://user-images.githubusercontent.com/25458928/79049130-e2429200-7c21-11ea-9a83-b078b242e880.png)

**Comment by Blueberryy** [comment]
add that mention to install guide then

**Comment by Gaerisson** [comment]
Already done, confirm to me that it is working with the beta :D and It will be good

( btw again, thanks for using my menu :3 )
